name: Copy Markdown file

on:
  repository_dispatch:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  copy-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Markdown file
        run: |
          curl -o other.md https://raw.githubusercontent.com/xx025/carrot/main/README.md
          sed -i '0,/<a/{/<a/d;}' other.md
          cat other.md >> .md
          cat other.md >> 1.md
          rm other.md
          echo "Hello, World!" > 1.md
          cat 1.md >> ../1.md
          cd ../
          pwd
          ls /home/runner/work/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
