name: Copy Markdown file

on:
  push:
    branches:
      - main

jobs:
  copy-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Markdown file
        run: |
          curl -o other.md https://raw.githubusercontent.com/xx025/carrot/main/README.md
          sed -i '0,/<a/{/<a/d;}' other.md
          cat other.md >> README.md
          rm other.md

      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add README.md
          git commit -m "Copy other.md to README.md and remove first <a> tag"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
