name: Copy Markdown file

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  copy-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy Markdown file
        run: |
          curl -o other.md https://raw.githubusercontent.com/xx025/carrot/main/README.md
          sed -i '0,/<a/{/<a/d;}' other.md
          cat other.md >> README.md
          rm other.md
          pwd
          git log -n 1
          pwd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
